# Name of the workflow
name: ReleaseMaster

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # git fetch --prune --unshallow --tags
      - name: Fetch latest tag
        id: tag_fetcher
        run: |
          git fetch --prune --unshallow --tags
          echo "Latest tag"
          git describe --tags --always
          git describe --tags --abbrev=0 --always
          echo '::set-output name=latest_tag::$(git describe --tags --always).zip'
          echo '::set-output name=latest_tag_alone::$(git describe --tags --abbrev=0 --always)'
          echo '::set-output name=latest_tag_name::$(git describe --tags  --always)'
          set nameoftag=$(git describe --tags  --always)

      - name: Print latest tag          
        run: echo "${{ steps.tag_fetcher.outputs.latest_tag_name }}"
      - name: Print latest tag normal          
        run: echo $nameoftag
      - name: Print latest tag complete          
        run: echo "${{ steps.tag_fetcher.outputs.latest_tag }}"

      - name: ReleaseMethod1
        run : echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${GITHUB_REF:10}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_fetcher.outputs.latest_tag_name }}
          release_name: Release ${{ steps.tag_fetcher.outputs.latest_tag_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false