# Name of the workflow
name: ReleaseMaster

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest tag
        id: tag_fetcher
        run: |
          git fetch --prune --unshallow --tags
          echo "Latest tag"
          git describe --tags
          git describe --tags --abbrev=0
          echo '::set-output name=latest_tag::$(git describe --tags).zip'
          echo '::set-output name=latest_tag_alone::$(git describe --tags --abbrev=0)'

      - name: Print latest tag          
        run: echo "${{ steps.tag_fetcher.outputs.latest_tag_alone }}"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v1.0.11
          release_name: Release v1.0.11
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false